name: pnpseismic
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - numpy>=1.15.0
  - scipy>=1.4.0
  - cudatoolkit=11.3
  - setuptools>=61.2.0
  - matplotlib
  - pylops
  - ipython
  - jupyter
  - pytorch==1.10.1
  - torchvision
  - pip:
    - cupy-cuda113
    - segyio
    - torchsummary
    - pyproximal
    - bm3d
