# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev36+g86481b2.d20221002'
__version_tuple__ = version_tuple = (0, 1, 'dev36', 'g86481b2.d20221002')
